[[IRBEM]]
arch = "aarch64"
git-tree-sha1 = "82ee27e5f5983d69736989f896ee45f86d996e41"
os = "macos"

    [[IRBEM.download]]
    sha256 = "a30755eaf40793ec1b9fadaafcff2430faf1f02f18e1489172d29a6837809ff4"
    url = "https://github.com/Beforerr/Libirbem_jll.jl/releases/download/IRBEM-v5.0.0+0/IRBEM.v5.0.0.aarch64-apple-darwin.tar.gz"
